[package]
name = "ocsp-stapler"
version = "0.4.5"
edition = "2021"
license = "MPL-2.0"
description = "OCSP stapler & client with support for Rustls"
authors = ["Igor Novgorodov <igor@novg.net>"]
homepage = "https://github.com/blind-oracle/ocsp-stapler"
repository = "https://github.com/blind-oracle/ocsp-stapler"
keywords = ["ocsp", "stapling", "staple", "rustls", "client"]
categories = [
    "network-programming",
    "cryptography",
    "asynchronous",
    "web-programming::http-server",
]

readme = "README.md"

[dependencies]
anyhow = "1.0"
arc-swap = "1"
base64 = "0.22"
bytes = "1.6"
chrono = "0.4"
http = "1.3"
itertools = { version = "0.14", optional = true }
prometheus = { version = "0.14", optional = true }
rasn = "0.15"
rasn-ocsp = "0.15"
rasn-pkix = "0.15"
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls-webpki-roots-no-provider",
    "http2",
    "charset",
    "macos-system-configuration",
] }
rustls = { version = "0.23", default-features = false, features = ["std"] }
sha1 = "0.10"
tokio = { version = "1.44", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }
tracing = "0.1"
url = "2.5"
x509-parser = "0.16"

[dev-dependencies]
hex-literal = "0.4"
rustls-pemfile = "2"
num-bigint = "0.4"
httptest = "0.16"

[lib]
doctest = false

[features]
default = ["prometheus", "ring"]
aws-lc-rs = ["rustls/aws_lc_rs"]
prometheus = ["itertools", "dep:prometheus"]
ring = ["rustls/ring"]

[build-dependencies]
readme-rustdocifier = "0.1.0"
